--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["CommonUI.Features.Label.Avatar"] = [[Avatar]],
	["CommonUI.Features.Label.Blog"] = [[Blog]],
	["CommonUI.Features.Label.BuildersClub"] = [[Klub Perakit]],
	["CommonUI.Features.Label.Catalog"] = [[Katalog]],
	["CommonUI.Features.Label.Chat"] = [[Obrolan]],
	["CommonUI.Features.Label.Events"] = [[Event]],
	["CommonUI.Features.Label.Friends"] = [[Teman]],
	["CommonUI.Features.Label.Game"] = [[Game]],
	["CommonUI.Features.Label.Groups"] = [[Grup]],
	["CommonUI.Features.Label.Help"] = [[Bantuan]],
	["CommonUI.Features.Label.Home"] = [[Beranda]],
	["CommonUI.Features.Label.Inventory"] = [[Inventaris]],
	["CommonUI.Features.Label.Messages"] = [[Pesan]],
	["CommonUI.Features.Label.More"] = [[Lainnya]],
	["CommonUI.Features.Label.Profile"] = [[Profil]],
	["CommonUI.Features.Label.Settings"] = [[Pengaturan]],
	["CommonUI.Features.Label.About"] = [[Tentang]],
	["CommonUI.Features.Label.Players"] = [[Pemain]],
	["CommonUI.Features.Label.Create"] = [[Buat]],
	["CommonUI.Features.Label.CreateGames"] = [[Buat Game]],
}