--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["CommonUI.Features.Label.Avatar"] = [[Avatar]],
	["CommonUI.Features.Label.Blog"] = [[Blog]],
	["CommonUI.Features.Label.BuildersClub"] = [[Builders Club]],
	["CommonUI.Features.Label.Catalog"] = [[Catalogo]],
	["CommonUI.Features.Label.Chat"] = [[Chat]],
	["CommonUI.Features.Label.Events"] = [[Eventi]],
	["CommonUI.Features.Label.Friends"] = [[Amici]],
	["CommonUI.Features.Label.Game"] = [[Giochi]],
	["CommonUI.Features.Label.Groups"] = [[Gruppi]],
	["CommonUI.Features.Label.Help"] = [[Guida]],
	["CommonUI.Features.Label.Home"] = [[Home]],
	["CommonUI.Features.Label.Inventory"] = [[Inventario]],
	["CommonUI.Features.Label.Messages"] = [[Messaggi]],
	["CommonUI.Features.Label.More"] = [[Altro]],
	["CommonUI.Features.Label.Profile"] = [[Profilo]],
	["CommonUI.Features.Label.Settings"] = [[Impostazioni]],
	["CommonUI.Features.Label.About"] = [[Info]],
	["CommonUI.Features.Label.Players"] = [[Giocatori]],
	["CommonUI.Features.Label.Create"] = [[Crea]],
	["CommonUI.Features.Label.CreateGames"] = [[Crea partite]],
}