--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["CommonUI.Features.Label.Avatar"] = [[アバター]],
	["CommonUI.Features.Label.Blog"] = [[ブログ]],
	["CommonUI.Features.Label.BuildersClub"] = [[ビルダーズ ・ クラブ]],
	["CommonUI.Features.Label.Catalog"] = [[カタログ]],
	["CommonUI.Features.Label.Chat"] = [[チャット]],
	["CommonUI.Features.Label.Events"] = [[イベント]],
	["CommonUI.Features.Label.Friends"] = [[友達]],
	["CommonUI.Features.Label.Game"] = [[ゲーム]],
	["CommonUI.Features.Label.Groups"] = [[グループ]],
	["CommonUI.Features.Label.Help"] = [[ヘルプ]],
	["CommonUI.Features.Label.Home"] = [[ホーム]],
	["CommonUI.Features.Label.Inventory"] = [[インベントリ]],
	["CommonUI.Features.Label.Messages"] = [[メッセージ]],
	["CommonUI.Features.Label.More"] = [[その他]],
	["CommonUI.Features.Label.Profile"] = [[プロフィール]],
	["CommonUI.Features.Label.Settings"] = [[設定]],
	["CommonUI.Features.Label.About"] = [[情報]],
	["CommonUI.Features.Label.Players"] = [[プレイヤー]],
	["CommonUI.Features.Label.Create"] = [[作成する]],
	["CommonUI.Features.Label.CreateGames"] = [[ゲームを作成する]],
}