--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["CommonUI.Features.Label.Avatar"] = [[Аватар]],
	["CommonUI.Features.Label.Blog"] = [[Блог]],
	["CommonUI.Features.Label.BuildersClub"] = [[Клуб создателей]],
	["CommonUI.Features.Label.Catalog"] = [[Каталог]],
	["CommonUI.Features.Label.Chat"] = [[Чат]],
	["CommonUI.Features.Label.Events"] = [[Акции]],
	["CommonUI.Features.Label.Friends"] = [[Друзья]],
	["CommonUI.Features.Label.Game"] = [[Игры]],
	["CommonUI.Features.Label.Groups"] = [[Группы]],
	["CommonUI.Features.Label.Help"] = [[Справка]],
	["CommonUI.Features.Label.Home"] = [[Главная]],
	["CommonUI.Features.Label.Inventory"] = [[Инвентарь]],
	["CommonUI.Features.Label.Messages"] = [[Сообщения]],
	["CommonUI.Features.Label.More"] = [[Больше]],
	["CommonUI.Features.Label.Profile"] = [[Профиль]],
	["CommonUI.Features.Label.Settings"] = [[Настройки]],
	["CommonUI.Features.Label.About"] = [[Сведения]],
	["CommonUI.Features.Label.Players"] = [[Игроки]],
	["CommonUI.Features.Label.Create"] = [[Создать]],
	["CommonUI.Features.Label.CreateGames"] = [[Создать игры]],
}