--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["CommonUI.Features.Label.Avatar"] = [[อวตาร]],
	["CommonUI.Features.Label.Blog"] = [[บล็อก]],
	["CommonUI.Features.Label.BuildersClub"] = [[ชมรมนักสร้าง]],
	["CommonUI.Features.Label.Catalog"] = [[แค็ตตาล็อก]],
	["CommonUI.Features.Label.Chat"] = [[แชต]],
	["CommonUI.Features.Label.Events"] = [[อีเวนต์]],
	["CommonUI.Features.Label.Friends"] = [[เพื่อน]],
	["CommonUI.Features.Label.Game"] = [[เกม]],
	["CommonUI.Features.Label.Groups"] = [[กลุ่ม]],
	["CommonUI.Features.Label.Help"] = [[ช่วยเหลือ]],
	["CommonUI.Features.Label.Home"] = [[หน้าหลัก]],
	["CommonUI.Features.Label.Inventory"] = [[คลังไอเทม]],
	["CommonUI.Features.Label.Messages"] = [[ข้อความ]],
	["CommonUI.Features.Label.More"] = [[เพิ่มเติม]],
	["CommonUI.Features.Label.Profile"] = [[ประวัติ]],
	["CommonUI.Features.Label.Settings"] = [[การตั้งค่า]],
	["CommonUI.Features.Label.About"] = [[เกี่ยวกับ]],
	["CommonUI.Features.Label.Players"] = [[ผู้เล่น]],
	["CommonUI.Features.Label.Create"] = [[สร้าง]],
	["CommonUI.Features.Label.CreateGames"] = [[สร้างเกม]],
}