--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["CommonUI.Features.Label.Avatar"] = [[Avatar]],
	["CommonUI.Features.Label.Blog"] = [[Blog]],
	["CommonUI.Features.Label.BuildersClub"] = [[Yapım Kulübü]],
	["CommonUI.Features.Label.Catalog"] = [[Katalog]],
	["CommonUI.Features.Label.Chat"] = [[Sohbet]],
	["CommonUI.Features.Label.Events"] = [[Etkinlikler]],
	["CommonUI.Features.Label.Friends"] = [[Arkadaşlar]],
	["CommonUI.Features.Label.Game"] = [[Oyunlar]],
	["CommonUI.Features.Label.Groups"] = [[Gruplar]],
	["CommonUI.Features.Label.Help"] = [[Yardım]],
	["CommonUI.Features.Label.Home"] = [[Ana Sayfa]],
	["CommonUI.Features.Label.Inventory"] = [[Envanter]],
	["CommonUI.Features.Label.Messages"] = [[Mesajlar]],
	["CommonUI.Features.Label.More"] = [[Daha Fazla]],
	["CommonUI.Features.Label.Profile"] = [[Profil]],
	["CommonUI.Features.Label.Settings"] = [[Ayarlar]],
	["CommonUI.Features.Label.About"] = [[Hakkında]],
	["CommonUI.Features.Label.Players"] = [[Oyuncular]],
	["CommonUI.Features.Label.Create"] = [[Oluştur]],
	["CommonUI.Features.Label.CreateGames"] = [[Oyun Oluştur]],
}