--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["CommonUI.Features.Label.Avatar"] = [[Hình đại diện]],
	["CommonUI.Features.Label.Blog"] = [[Blog]],
	["CommonUI.Features.Label.BuildersClub"] = [[Câu lạc bộ Thợ xây]],
	["CommonUI.Features.Label.Catalog"] = [[Danh mục]],
	["CommonUI.Features.Label.Chat"] = [[Trò chuyện]],
	["CommonUI.Features.Label.Events"] = [[Sự kiện]],
	["CommonUI.Features.Label.Friends"] = [[Bạn bè]],
	["CommonUI.Features.Label.Game"] = [[Trò chơi]],
	["CommonUI.Features.Label.Groups"] = [[Nhóm]],
	["CommonUI.Features.Label.Help"] = [[Trợ giúp]],
	["CommonUI.Features.Label.Home"] = [[Trang chủ]],
	["CommonUI.Features.Label.Inventory"] = [[Kho]],
	["CommonUI.Features.Label.Messages"] = [[Tin nhắn]],
	["CommonUI.Features.Label.More"] = [[Thêm]],
	["CommonUI.Features.Label.Profile"] = [[Hồ sơ]],
	["CommonUI.Features.Label.Settings"] = [[Cài đặt]],
	["CommonUI.Features.Label.About"] = [[Về sản phẩm]],
	["CommonUI.Features.Label.Players"] = [[Người chơi]],
	["CommonUI.Features.Label.Create"] = [[Tạo]],
	["CommonUI.Features.Label.CreateGames"] = [[Tạo trò chơi]],
}