return function()
	local Modules = game:GetService("CoreGui").RobloxGui.Modules
	local ScreenSize = require(Modules.LuaApp.Reducers.ScreenSize)
	local SetScreenSize = require(Modules.LuaApp.Actions.SetScreenSize)
	local defaultScreenSize = Vector2.new(0, 0)
	it("should return default value when init", function()
		local state = ScreenSize(nil, {})
		expect(type(state)).to.equal("userdata")
		expect(state).to.equal(defaultScreenSize)
	end)
	it("should be unchanged by other actions", function()
		local oldState = ScreenSize(nil, {})
		local newState = ScreenSize(oldState, { type = "not SetScreenSize" })
		expect(newState).to.equal(oldState)
		expect(newState).to.equal(defaultScreenSize)
	end)
	it("should update ScreenSize when dispatch SetScreenSize action", function()
		local newScreenSize = Vector2.new(100, 100)
		local oldState = ScreenSize(nil, {})
		local newState = ScreenSize(oldState, SetScreenSize(newScreenSize))
		expect(newState).never.to.equal(oldState)
		expect(newState).to.equal(newScreenSize)
	end)
end