metadata.config_version_wildcard = "0.53.*"

[game_setup]
# Aliases for "v348" is "2018M", "v463" is "2021E".
roblox_version = '2018'

[game_setup.persistence]
sqlite_path = '_.sqlite'
clear_on_start = false

[server_core.metadata]
title = 'òó'
description = ''
creator_name = 'ÒÓ'
icon_uri = 'c:\Users\USERNAME\Pictures\Byfron Icon.png'

[server_core.place_file]
# Can be a file path or an online resource through HTTP(S).
rbxl_uri = '_.rbxl'

# When game:SavePlace() is called, overwrites the place at `rbxl_uri`.
# Doesn't work if `rbxl_uri` points to an online resource.
enable_saveplace = false

[server_core]
startup_script = 'game.workspace.FilteringEnabled = true'
retrieve_default_user_code = '''
function(tick) -- float -> str
    return string.format('Player%d', tick)
end
'''

check_user_allowed = '''
function(user_iden, user_code) -- string -> bool
    return true
end
'''

retrieve_avatar_type = '''
function(user_iden, user_code)
    return 'R6'
end
'''

retrieve_avatar_items = '''
function(user_iden, user_code)
    if user_code == 'VisualPlugin' then
        return {
            10726856854,
            9482991343,
            9481782649,
            9120251003,
            4381817635,
            6969309778,
            5731052645,
            2846257298,
            121390054,
            261826995,
            154386348,
            201733574,
            48474294,
            6340101,
            192483960,
            190245296,
            183808364,
            34247191,
        }
    end
    return {}
end
'''

retrieve_avatar_colors = '''
function(user_iden, user_code)
    if user_code == 'VisualPlugin' then
        return {
            head = 315,
            left_arm = 315,
            left_leg = 315,
            right_arm = 315,
            right_leg = 315,
            torso = 315,
        }
    end
    return {
        head = BrickColor.Random().Number,
        left_arm = BrickColor.Random().Number,
        left_leg = BrickColor.Random().Number,
        right_arm = BrickColor.Random().Number,
        right_leg = BrickColor.Random().Number,
        torso = BrickColor.Random().Number,
    }
end
'''

retrieve_avatar_scales = '''
function(user_iden, user_code)
    return {
        height = 1,
        width = 1,
        head = 1,
        depth = 1,
        proportion = 1,
        body_type = 1,
    }
'''

retrieve_username = '''
def f(user_id_num, user_code):
    return user_code
'''

filter_text = '''
def f(text, user_id_num, user_code):
    return (
        text
        .replace('oo','òó')
        .replace('OO','ÒÓ')
        .replace('ee','èé')
        .replace('EE','ÈÉ')
        .replace('Roblox','Rōblox')
        .replace('ROBLOX','RŌBLOX')
    )
'''

retrieve_groups = '''
function(user_iden, user_code)
    return {
        ['1200769'] = 255;
        ['2868472'] = 255;
        ['4199740'] = 255;
        ['4265462'] = 255;
        ['4265456'] = 255;
        ['4265443'] = 255;
        ['4265449'] = 255;
    }
end
'''

retrieve_default_funds = '''
def f(*a):
    return 6969
'''

chat_style = 'ClassicAndBubble'

[[remote_data.badges]]
id_num = 163231044
name = 'EnforcersPowers'

[[remote_data.gamepasses]]
id_num = 163231044
name = 'EnforcersPowers'
price = 1

[[remote_data.gamepasses]]
id_num = 163230957
name = 'DoubleCash'
price = 1

[[remote_data.gamepasses]]
id_num = 163230779
name = 'DriversLicense'
price = 1

[[remote_data.gamepasses]]
id_num = 163231101
name = 'ClubRed'
price = 1

[[remote_data.gamepasses]]
id_num = 170212491
name = 'UnrestrictedDJ'
price = 1

[[remote_data.gamepasses]]
id_num = 170211728
name = 'House'
price = 1

[[remote_data.gamepasses]]
id_num = 203877255
name = 'VIP'
price = 1
