GIT_RELEASE_VERSION = '''2024-03-30T16꞉30Z'''

DEFAULT_PLACE_ID = 1818

DEFAULT_APPEARANCE = "rbxassetid://6445262286;rbxassetid://2510230574;rbxassetid://2510233257;rbxassetid://2510236649;rbxassetid://2510238627;rbxassetid://6969309778;rbxassetid://2846257298;rbxassetid://6340101;rbxassetid://34247191;rbxassetid://48474294;rbxassetid://107458429;rbxassetid://121390054;rbxassetid://154386348;rbxassetid://183808364;rbxassetid://190245296;rbxassetid://192483960;rbxassetid://201733574;rbxassetid://261826995;rbxassetid://9120251003;rbxassetid://9481782649;rbxassetid://9482991343;rbxassetid://5731052645;rbxassetid://10726856854;password=1630228|Cyan;Cyan;Cyan;Cyan;Cyan;Cyan"

CLIENT_SETTINGS = {
    "DebugLocalRccServerConnection": "True",
    "DFIntCrashUploadToBacktracePercentage": "10",
    "DFStringCrashUploadToBacktraceBlackholeToken": "7705528468a303e4e34a13fbcf9e42e219633ed6868e143e5ab16cd33bd2a069",
    "DFStringCrashUploadToBacktraceMacPlayerToken": "24cb37449e120c3a0618b1bf0585e339571828cae4dc73c7b8c99f67fcd751e9",
    "DFStringCrashUploadToBacktraceWindowsPlayerToken": "417ecb0fbc032ce087e6af3b780c298e3356089f050c8130d2318109e80417a4",
    "DFStringHttpInfluxDatabase": "prod",
    "FFlagDebugCrashEnabled": "False",
    "FLogFastLogValueChanged": "0",
    "GoogleAnalyticsAccountPropertyID": "UA-43420590-3",
    "GoogleAnalyticsAccountPropertyIDPlayer": "UA-43420590-14",
    "COPY_FROM_HERE_TO_OTHER_ENV_DO_NOT_CHANGE_ABOVE_FLAGS": "False",
    "AllowVideoPreRoll": "True",
    "AxisAdornmentGrabSize": "12",
    "CaptureCountersIntervalInMinutes": "5",
    "CaptureQTStudioCountersEnabled": "True",
    "DFFlagAccoutrementWeldingFilteringEnabled": "False",
    "DFFlagAdjustShorterLegLength": "True",
    "DFFlagAdjustSittingHeight": "True",
    "DFFlagAdjustSittingHeightWithMeasurements": "True",
    "DFFlagAllTogetherNow": "True",
    "DFFlagAllowJoinsToWait": "True",
    "DFFlagAlternateScalingForAccessories": "True",
    "DFFlagAlternateScalingForNativeParts": "True",
    "DFFlagAlternateScalingForNativePartsV3": "True",
    "DFFlagAnalyticsNewDtors": "True",
    "DFFlagAndroidAlsoFetchSettingsFromNewEndpoint": "True",
    "DFFlagAndroidReportTimeToFetchSettings": "True",
    "DFFlagAniCoalesce": "True",
    "DFFlagAniLongCycleFix": "True",
    "DFFlagAnimatorOnSteppedKeepAlive": "True",
    "DFFlagAvatarJointPositionsEnabled": "True",
    "DFFlagBetterShutdownEphemeralReportingThreads": "True",
    "DFFlagBgUpdateRedirects": "True",
    "DFFlagBuiltInPluginsCanModifyHttpEnabled": "True",
    "DFFlagCLI120342": "False",
    "DFFlagCLI16089_2": "True",
    "DFFlagCSGMeshLevelOfDetail": "False",
    "DFFlagCSGMeshLevelOfDetail_Fix1": "False",
    "DFFlagCSGMeshV4DeserializerEnabled": "True",
    "DFFlagCSGNewLimit": "True",
    "DFFlagCSGv2SkipDegenerateTriangles": "True",
    "DFFlagCSGv2StatisticsFix": "True",
    "DFFlagCSGv2UseMegaAssetFetcher": "True",
    "DFFlagCSGv2UsePositionClustering": "True",
    "DFFlagCannotReplicateWithRespectToSubAssembly": "True",
    "DFFlagCantGetMad2": "True",
    "DFFlagCheckMultipleLoadCharacterCalls": "True",
    "DFFlagCleanCacheMoveMutex": "True",
    "DFFlagClearNetworkPhysicsDataOnSpatialFilter": "True",
    "DFFlagClientJoinProcessToEventIngest": "True",
    "DFFlagClientsCombinedAniEvent": "True",
    "DFFlagCloudEditPublishNoStream2": "True",
    "DFFlagCrashUploadIgnoreExceptionsInFileAttachments": "True",
    "DFFlagCrashUploadUseBacktraceOnly": "True",
    "DFFlagCyclicExecutiveThrottlingCancelWorldStepAccum": "False",
    "DFFlagDataStoreAutoHttpRetry": "False",
    "DFFlagDataStoresP50": "False",
    "DFFlagDebugGAReportThrottledSessions": "True",
    "DFFlagDebugLaunchTimeByCountryPlaceSpecific_PlaceFilter": "true;189707",
    "DFFlagDefaultArtistIntentJoints": "True",
    "DFFlagDefaultArtistIntentJoints_PlaceFilter": "True;1436365469;2214171804;175063958;2185699092;2379593218;1402361425;30036724;171980054;1863446194;2380458516;189707;190887495;2316961408;2385489332;1511054578;2031410176;2405149146;2333626326;2410999210;2371791457;1372241777;2357232800;306503935;2214171804;2185699092;1863446194;1417427737;164051105;1828509885;132414630;1468955878;1868999426;2230731085;2099342453;2218695613;2462786030;2431195974",
    "DFFlagDeferTerrainUpdate": "False",
    "DFFlagDeleteBeforeClear": "True",
    "DFFlagDeprecatableBroadcasts": "True",
    "DFFlagDescendentChangedSignalEnabled": "True",
    "DFFlagDisableLuaBridgeForRemoteRccMicroprofiles": "True",
    "DFFlagDisableTearDownFastLog": "True",
    "DFFlagDistributeNetworkOwnershipServeronly": "True",
    "DFFlagDoNotRunAnimationEditorInPlayMode": "True",
    "DFFlagDoesItHalt": "True",
    "DFFlagDontApplyCharacterFloorVelocityFix": "True",
    "DFFlagDontCallOnMovingAssemblyRoot": "False",
    "DFFlagDontRemoveGUIDEarly": "True",
    "DFFlagDontWhitelistUserInputConnectionCounts": "True",
    "DFFlagDynamicLocalizationTableIgnoreNullAssets": "True",
    "DFFlagDynamicLocalizationTables2": "True",
    "DFFlagDynamicLocalizationTables2_PlaceFilter": "True;1117775855",
    "DFFlagDynamicReloaderDoWork": "True",
    "DFFlagEnableMeshHeadAttachments": "True",
    "DFFlagEnableMeshHeadNative": "True",
    "DFFlagEnableRemoteProfiling": "True",
    "DFFlagEnableWakingPGSJointsForNonSolverPrimitives": "True",
    "DFFlagEnforceSlaveStateEnabledStatus": "True",
    "DFFlagExternalWakeOtherAssembly2": "False",
    "DFFlagFavorIPV4Connections": "False",
    "DFFlagFindClosestHandleHitTestFixEnabled": "True",
    "DFFlagFireCharacterAddedAfterSpawn": "False",
    "DFFlagFireHealthChangedLater": "True",
    "DFFlagFixCharacterAppearanceLoadedEvent": "True",
    "DFFlagFixCharacterAppearanceLoadedEvent2": "True",
    "DFFlagFixCharacterStuckInFreefall": "True",
    "DFFlagFixCrashInSanitizeCustomGui": "True",
    "DFFlagFixCrashInTeleportToPrivateServer": "True",
    "DFFlagFixCustomWeldSeatPart": "True",
    "DFFlagFixCutAndUndoAfterSavingCSGUnionToNewFile": "True",
    "DFFlagFixFirstPersonSwimmingStateChange": "True",
    "DFFlagFixFreefallStuckIgnoreSelfContact": "True",
    "DFFlagFixLocalSpaceInterpolationUseCorrectGUID": "True",
    "DFFlagFixMeshNormalsForNonUniformScaling": "True",
    "DFFlagFixMissingLocalSpaceFloorInterpolation": "True",
    "DFFlagFixPartSetterWeldConstraintHandling": "True",
    "DFFlagFixSetupAnimationWeights": "True",
    "DFFlagFixSteepSlopeSliding": "True",
    "DFFlagFixStudioPositionAndOrientationPropertyWeldConstraints": "True",
    "DFFlagFixTinyFishScales": "True",
    "DFFlagFixTinyMeshScales2": "True",
    "DFFlagGetTeamLazyEvaluation": "True",
    "DFFlagGoodbyeChoiceActiveProperty": "True",
    "DFFlagGroupTeleportAddTeleportIdParameter": "True",
    "DFFlagHttpAddCsrfForNonGet": "True",
    "DFFlagHttpAddRbxHeaders": "True",
    "DFFlagHttpAnalyticsType": "True",
    "DFFlagHttpBatchCompress": "True",
    "DFFlagHttpBatchSecure": "True",
    "DFFlagHttpCacheMissingRedirects": "True",
    "DFFlagHttpCalculateHashFix": "True",
    "DFFlagHttpCheckMethod": "True",
    "DFFlagHttpClientDisabledSkipCache": "True",
    "DFFlagHttpFixEmptyErrorMsg": "True",
    "DFFlagHttpFixStatusErrorMsg": "True",
    "DFFlagHttpFollowAllRedirects": "True",
    "DFFlagHttpNew2": "True",
    "DFFlagHttpRbxApiRequestAsync": "True",
    "DFFlagHttpReportStatisticsNew": "False",
    "DFFlagHttpUrlDecodeFix": "True",
    "DFFlagHttpUrlPortFix": "True",
    "DFFlagHttpUrlSubdomainDotFix": "True",
    "DFFlagHttpZeroLatencyCaching": "True",
    "DFFlagHumanoidSimulateIfWorld": "True",
    "DFFlagHumanoidWithPGSConstraintsUsePhysicsState": "True",
    "DFFlagIncludeServerInfoInCrashAttributes": "True",
    "DFFlagInfluxOverTCP": "False",
    "DFFlagJointActiveEnabled2": "True",
    "DFFlagKhanovichBrokeStairClimbingShameOnHim": "True",
    "DFFlagLegacySolverOverrideDeserializeUnthrottled": "False",
    "DFFlagLegacySolverOverrideUiUnthrottled": "True",
    "DFFlagLocalizationAnalyticsLetterContentOnly": "True",
    "DFFlagLockTheftInstanceCrash": "True",
    "DFFlagLockViolationInstanceCrash": "False",
    "DFFlagLockViolationScriptCrash": "False",
    "DFFlagLogGroupTeleportInfluxDB": "True",
    "DFFlagLogMemoryStatsOnCompressionError": "True",
    "DFFlagLuaAPIGetCharacterAppearanceMorpherFix": "True",
    "DFFlagMacClientAlsoFetchSettingsFromNewEndpoint": "True",
    "DFFlagMacClientReportTimeToFetchSettings": "True",
    "DFFlagMacPlayerTransferCookiesToUpsellBrowser": "True",
    "DFFlagMatchProdBaseProto": "True",
    "DFFlagMoreStreamingAnalytics": "True",
    "DFFlagMoreWeldRestrictions": "False",
    "DFFlagMovePhysicsReprocessToStudio": "True",
    "DFFlagNPCUnequipTools": "True",
    "DFFlagNamesOccludedAsDefault": "True",
    "DFFlagNavigationServiceAnalytics": "True",
    "DFFlagNetworkStreamThrowReadPast": "True",
    "DFFlagNewHttpAnalytics": "True",
    "DFFlagNewInfluxDbThreadPool": "True",
    "DFFlagNewJumpingControllerAlongWithPD": "False",
    "DFFlagNewPDControllerHumanoid": "True",
    "DFFlagNewSenderDontGoBacktoZero": "True",
    "DFFlagNewSortAndFilter": "True",
    "DFFlagNoInfiniteLoopOnChatInfoLoadFailure": "True",
    "DFFlagNormalizeForcedLocales": "True",
    "DFFlagNotTouching2": "True",
    "DFFlagOnlyFireHealthChangedWhenHealthChanges": "True",
    "DFFlagOrder66": "False",
    "DFFlagPGSByDefault": "False",
    "DFFlagPGSSolverSimIslandsEnabled2": "True",
    "DFFlagPGSWakeOtherAssemblyForJoints": "True",
    "DFFlagPGSWakeOtherIfOneAssemblyIsAwake": "False",
    "DFFlagPackageAnalyticsOnCloudEdit": "True",
    "DFFlagPartyPooperSecurity": "True",
    "DFFlagPhysicsMegaReplicator_PlaceFilter": "True;1034242130;189707",
    "DFFlagPhysicsResetOsp": "True",
    "DFFlagPhysicsSenderOpt": "True",
    "DFFlagPhysicsSenderStreamingEnabledCheckContainer": "True",
    "DFFlagPhysicsSenderUseMakeShared": "True",
    "DFFlagPhysicsSkipNonRealTimeHumanoidForceCalc": "False",
    "DFFlagPrepareClientForNewJoinData": "True",
    "DFFlagPreserveJointsOnSpawn": "True",
    "DFFlagPreventReturnOfElevatedPhysicsFPS": "True",
    "DFFlagProcessHardware": "True",
    "DFFlagProtectNullRakPeer": "True",
    "DFFlagRCCMonitoringCacheHeartbeat": "True",
    "DFFlagRagdollNotSuperAnnoying": "True",
    "DFFlagRakNetDetectNetUnreachable": "True",
    "DFFlagRbxFormatMultiByteSizeFix": "True",
    "DFFlagRccAlsoFetchSettingsFromNewEndpoint": "True",
    "DFFlagRccFetchSettingsDirectlyFromService": "True",
    "DFFlagRccFetchSettingsWithCorrectApplicationNameFromCdn": "True",
    "DFFlagRccGameServerInitializationByDataCenter": "True",
    "DFFlagRccReportTimeToFetchSettings": "True",
    "DFFlagRccTrackSettingsRefreshFailures": "True",
    "DFFlagReduceTrussSearchDistance": "False",
    "DFFlagRenderGatherMsFrame": "True",
    "DFFlagReplicatorCollectItemCountOnSend": "True",
    "DFFlagReplicatorEnforceTopContainerCountLimit": "True",
    "DFFlagReplicatorEnforceVariantContainerCountLimit": "True",
    "DFFlagReplicatorExplicitMegaReplicatorDisconnectState": "True",
    "DFFlagReplicatorLabelItemTypesProcessed": "True",
    "DFFlagReplicatorPacketStatsHandleBursts": "True",
    "DFFlagReplicatorRemovePropBrickColorExclusion": "True",
    "DFFlagReportCharacterLoadTimeMetrics2": "True",
    "DFFlagReportClientMemoryCat": "True",
    "DFFlagReportDataPingByPlayerBin": "True",
    "DFFlagReportGARenderMsFrameMetrics": "True",
    "DFFlagReportGPUMetrics": "True",
    "DFFlagReportInfluxRenderMsFrameMetrics": "True",
    "DFFlagReportRCCRealTimeSimulationStats": "True",
    "DFFlagReportRCCStatToInflux": "True",
    "DFFlagReportSmoothHeartbeat": "True",
    "DFFlagReportSolverUsageStats": "True",
    "DFFlagRequestAsyncEmptyHeaderFix": "True",
    "DFFlagScaleAllAccessories2": "True",
    "DFFlagSendClientNewJoinData": "True",
    "DFFlagSendFrameTimeBreakdowns": "True",
    "DFFlagServerCopiesPlayerGuiSetTimeFix": "True",
    "DFFlagServerGenPlayerXboxFixTag": "True",
    "DFFlagServerReplicatorMinimizePropSync": "True",
    "DFFlagServerReportRealTimePlayersCountForRealtimeStats": "True",
    "DFFlagSetSimulationRadiusInPhysicsSender": "True",
    "DFFlagSimplifyRakNetConnectionHandshake": "False",
    "DFFlagSkipTagging": "True",
    "DFFlagSmootherVehicleSeatControlSystem": "True",
    "DFFlagSpecialCaseSupportRbxCdnInAppDataModel2": "True",
    "DFFlagSpecificGravityDummyFunctionGA": "True",
    "DFFlagSpecificGravityDummyReturnsZero": "False",
    "DFFlagSteadyAni_PlaceFilter": "True;370731277",
    "DFFlagStopFrequentConversion": "True",
    "DFFlagStopStopping": "True",
    "DFFlagStreamAlwaysCheckBeforeStreaming2": "True",
    "DFFlagStreamAlwaysCheckPrimInsert2": "True",
    "DFFlagStreamCountClustersInClientQuota": "True",
    "DFFlagStreamingRadiusAPIControl": "True",
    "DFFlagStudioNotificationForSolverDeprecation": "False",
    "DFFlagTeleportPartyAsyncEnable": "True",
    "DFFlagTextScraperHasServerMessageLimit": "True",
    "DFFlagTextScraperHasServerMessageLimit_PlaceFilter": "True;1117775855",
    "DFFlagThrottleDebuggerMetrics": "True",
    "DFFlagThrottleGetUserThumbnailAsync": "True",
    "DFFlagThrottleOnlyBasedOnWorldStep": "True",
    "DFFlagThrowOnCompressionError": "True",
    "DFFlagTrackHopperBinUsage2": "True",
    "DFFlagUWPAlsoFetchSettingsFromNewEndpoint": "True",
    "DFFlagUWPReportTimeToFetchSettings": "True",
    "DFFlagUpdateNetworkSleepingOnAllAssemblyChildren": "True",
    "DFFlagUploadPlaceNoStream2": "True",
    "DFFlagUseCombinedAnimationEvent": "True",
    "DFFlagUseDistanceThinning": "True",
    "DFFlagUseHttpsAnalyticsUrls": "True",
    "DFFlagUseMegaReplicationCaching3": "True",
    "DFFlagUseMegaReplicationData3": "True",
    "DFFlagUseMomentumThinning": "True",
    "DFFlagUseMomentumThinning_PlaceFilter": "False;1694497805;1225846869",
    "DFFlagUseNewLeakyBucketForRateLimiting_v2": "True",
    "DFFlagUseRoundRobin": "False",
    "DFFlagUseSort": "False",
    "DFFlagUserAccessUserSettings": "True",
    "DFFlagUserAllowDisableCustomAnims2": "True",
    "DFFlagUserChatPrivacySetting": "True",
    "DFFlagUserFixCharacterSoundIssues": "True",
    "DFFlagUserHttpAPIEnabled": "True",
    "DFFlagUserInputServiceProcessOnRender": "True",
    "DFFlagUserPlayCharacterLoopSoundWhenFE": "True",
    "DFFlagUserPlayCharacterSoundWhenFE": "True",
    "DFFlagUserPreloadAnimations": "True",
    "DFFlagUserServerFollowers": "True",
    "DFFlagUserUseLuaVehicleController": "True",
    "DFFlagUserUseSoundDispatcher": "True",
    "DFFlagWhitelistUserInputEvents": "True",
    "DFFlagWindowsClientAlsoFetchSettingsFromNewEndpoint": "True",
    "DFFlagWindowsClientImprovedWebViewCookieSupport": "True",
    "DFFlagWindowsClientReportTimeToFetchSettings": "True",
    "DFFlagWorkspaceNotificationMasterEnable": "False",
    "DFFlagXboxAlsoFetchSettingsFromNewEndpoint": "True",
    "DFFlagXboxReportTimeToFetchSettings": "True",
    "DFFlagiOSAlsoFetchSettingsFromNewEndpoint": "True",
    "DFFlagiOSReportTimeToFetchSettings": "True",
    "DFIntAnalyticsMaxSendWaitTimeMs": "1500",
    "DFIntAndroidInfluxHundredthsPercentage": "0",
    "DFIntAniCycleCount": "0",
    "DFIntApiRateLimit": "200",
    "DFIntAvatarAPIAvatarFetchRolloutV2": "100",
    "DFIntBgUpdateRedirectsHttpErrInfluxHundredthsPercentage": "100",
    "DFIntBroadPhaseIslandBufferZoneMinPartLimit": "0",
    "DFIntBroadPhaseIslandBufferZoneMinPartLimit_PlaceFilter": "5;1105449649",
    "DFIntBulletContactBreakOrthogonalThresholdPercent": "200",
    "DFIntBulletContactBreakThresholdPercent": "200",
    "DFIntCSGLevelOfDetailSwitchingDistance": "250",
    "DFIntCSGv2LodMinTriangleCount": "100",
    "DFIntCSGv2OperationInfluxHundredthsPercentage": "100",
    "DFIntClientJoinProcessPositiveSamplesThousandths": "10",
    "DFIntClientNetworkInfluxHundredthsPercentage": "1000",
    "DFIntCrashUploadHttpResponseDefaultTimeoutMillis": "80000",
    "DFIntDataStoreInfluxReportNonParsableDataPerMyriad": "10000",
    "DFIntDataStoreMaxValueSize": "262144",
    "DFIntDefaultBalanceD": "100",
    "DFIntDefaultBalanceP": "7000",
    "DFIntDraggerMaxMovePercent": "60",
    "DFIntDynamicReloaderFailureInfluxHundrethsPercentage": "10000",
    "DFIntElevatedPhysicsFPSReportThresholdTenths": "585",
    "DFIntExpireMarketPlaceServiceCacheSeconds": "60",
    "DFIntGamePassOwnershipCacheSeconds": "30",
    "DFIntGetUserThumbnailAsyncThrottleTime": "3",
    "DFIntHttpBatchAssetV1HundredthsPercentage": "10000",
    "DFIntHttpCacheCleanMaxFilesToKeep": "7500",
    "DFIntHttpCacheCleanMinFilesRequired": "10000",
    "DFIntHttpCurlConnectionCacheSize": "-1",
    "DFIntHttpInfluxHundredthsPercentage": "5",
    "DFIntHttpSendStatsEveryXSeconds": "300",
    "DFIntICMPPingHundrethsPercentage": "0",
    "DFIntInfluxReportLocalFilterStringPermyriad": "500",
    "DFIntInfluxReportRCCStatsHundredthsPercentage": "5000",
    "DFIntJoinInfluxHundredthsPercentage": "100",
    "DFIntLogGroupTeleportInfluxPerTenThousand": "1000",
    "DFIntMacInfluxHundredthsPercentage": "0",
    "DFIntMaxClusterKBPerSecond": "400",
    "DFIntMaxDataPayloadSize": "96000000",
    "DFIntMaxFramesToSend": "2",
    "DFIntMaxMissedWorldStepsRemembered": "16",
    "DFIntNewSettingsEndpointExceptionInfluxPermyriad": "10000",
    "DFIntNumberFramesSubmergedBeforeVSquaredViscocity_PlaceFilter": "0; 1221071288; 1107780422; 1223560318",
    "DFIntPartSizeUnder0P2AnalyticsInfluxHundredthPct": "100",
    "DFIntPercentApiRequestsRecordGoogleAnalytics": "0",
    "DFIntPhysicsDecompSerialVersion": "5",
    "DFIntPrimStatsGANumDelimited": "3000",
    "DFIntRakNetConnectionStartWindow_HundredthsPercentage": "1000",
    "DFIntRakNetResendMaxThresholdTimeInUs": "2000000",
    "DFIntRakNetResendScaleBackFactorHundredthsPercent": "6500",
    "DFIntRenderMsFrameInfluxHundredthsPercentage": "10",
    "DFIntReplicatorCountLimitInfluxHundrethsPercentage": "10000",
    "DFIntReplicatorMaxPacketBytesSentToInfluxOnError": "256",
    "DFIntReportDeviceInfoRate": "100",
    "DFIntS2NumPhysicsPacketsPerStep": "2",
    "DFIntS2PhysicsSenderRate": "15",
    "DFIntSendJoinTimeDeltasToDiag_HundredthsPercentage": "100",
    "DFIntSendJoinTimesToDiag_HundredthsPercentage_PlaceFilter": "4000;370731277",
    "DFIntSendRakNetStatsInterval": "300",
    "DFIntSendRakNetStatsThrottle": "2",
    "DFIntSmoothTerrainPhysicsRayAabbSlop": "1",
    "DFIntSoundFill": "83333",
    "DFIntSoundLeak": "10000000",
    "DFIntSpecialFill": "0",
    "DFIntSpecialLeak": "111111",
    "DFIntStepsToJoin": "2",
    "DFIntStreamJobMaxBufferHealthThresholdHundredths": "75",
    "DFIntStreamJobMaxBufferHealthThresholdHundredths_PlaceFilter": "50;1526666203",
    "DFIntStreamJobMinBufferHealthThresholdHundredths": "40",
    "DFIntStreamJobMinBufferHealthThresholdHundredths_PlaceFilter": "30;1526666203",
    "DFIntTargetTimeDelayFacctorTenths": "20",
    "DFIntTeleportExceptionInfluxHundredthsPercentage": "9000",
    "DFIntThrottledVelocityThresholdTenths": "15",
    "DFIntTimePermyriad": "10000",
    "DFIntWaterViscosityDragFudgeFactor_PlaceFilter": "500; 1221071288; 1107780422; 1223560318",
    "DFIntWebParserInfluxWriteNanInfPerMyriad": "1000",
    "DFIntWeldPermyriad": "100",
    "DFIntWorldStepDtAveExpFactorHundredth": "1",
    "DFLogErrorDescription": "6",
    "DFLogLuaTypeErrors": "4",
    "DFLogSoundCheckResult": "4",
    "DFLogSoundTrace": "4",
    "DFStringAdditionalBlacklistHeaders": "SOAPAction",
    "DFStringDataStoreThrottleMsg": "DataStore request was added to queue. If request queue fills, further requests will be dropped. Try sending fewer requests. Key =",
    "DFStringGamePerfMonitorPercentageCountryOverride": "CN,50,AU,50,NZ,50",
    "DFStringOverrideSendRakNetStatsThrottleCountries": "CN,50",
    "DFStringR15CollisionTypeField": "universeAvatarCollisionType",
    "DFStringRobloxAnalyticsURL": "http://web.archive.org/web/20190107002714/http://ecsv2.roblox.com/",
    "DFStringSendJoinTimeDeltasHundPrecCountryOverride": "CN,5000,US,100,AU,3000,KR,2000,NZ,3000",
    "DFStringSendJoinTimeStatsHundPrecCountryOverride": "CN,5000,US,100,AU,3000,KR,2000,NZ,3000",
    "DFStringSendJoinTimeStatsHundPrecCountryOverride_PlaceFilter": "CN,10000,US,10000,AU,10000,KR,10000,NZ,10000;189707",
    "DFStringSendPingForCnConnectingToDcList": "111,174,191,133",
    "DFStringWorkspaceMessageLink": "http://web.archive.org/web/20190107002714/https://devforum.roblox.com/t/physics-deprecating-the-legacy-spring-physics-solver/163521",
    "DFStringWorkspaceMessageText": "We are in the process of disabling and removing the legacy solver.  Click here for more info...",
    "FFlagAddEndedSignalToSoundJobStudio": "True",
    "FFlagAdjustHipTranslationBasedOnHipHeight": "True",
    "FFlagAdvancedMouseSensitivityEnabled": "True",
    "FFlagAllowAddWindowWithIdWithoutDataModel": "True",
    "FFlagAllowLocaleIdForcing": "True",
    "FFlagAlwaysBindToDataServiceStopWait": "True",
    "FFlagAlwaysFireErrorSignal": "True",
    "FFlagAndroidFixWrongSurfaceShutdown": "True",
    "FFlagAndroidLeaveOtherEntryBeforeJoin2": "True",
    "FFlagAndroidShutdownViewFix": "True",
    "FFlagAnthroArtistIntentFBXImporterIntermediateState": "False",
    "FFlagAppBackgroundMode2": "True",
    "FFlagAppShellReporterMonitorFrameTimeIOS": "True",
    "FFlagArrayDynamicReserveUsesMoveSemantic": "False",
    "FFlagArrowByGraphemesInTextbox": "True",
    "FFlagAvatarEditorAddPresetCostumes": "True",
    "FFlagAvatarEditorAnthroSlidersUIOnly": "True",
    "FFlagAvatarEditorDefaultTabSelection": "True",
    "FFlagAvatarEditorFixLoadAnimation": "True",
    "FFlagAvatarEditorFixMissingPartError": "True",
    "FFlagAvatarEditorFixOutfitDispatch": "True",
    "FFlagAvatarEditorFixPlatformHeight": "True",
    "FFlagAvatarEditorFixPropertyNameString": "True",
    "FFlagAvatarEditorFixTShirtGraphic": "True",
    "FFlagAvatarEditorHideSliderHighlightOnInit": "True",
    "FFlagAvatarEditorImproveCamera": "True",
    "FFlagAvatarEditorRecomputeCameraLookAt": "False",
    "FFlagAvatarEditorRoactRewrite": "True",
    "FFlagAvatarEditorSelectivelyUseDefaultAsset": "True",
    "FFlagAvatarEditorUseArtistIntentFolder": "True",
    "FFlagAvatarEditorUseAvatarRulesForScales": "True",
    "FFlagAvatarEditorUseNewCostumeLogic": "True",
    "FFlagAvatarEditorUseNewR15Model": "True",
    "FFlagAvatarEditorUseTopBarHeight": "True",
    "FFlagAvatarPartScaleTypeFix": "True",
    "FFlagAvoidFindFirstChildCallsInGuiBase2d": "True",
    "FFlagAvoidNDKNewStringUTF": "True",
    "FFlagBackpackScriptUseFormatByKey": "False",
    "FFlagBadgeReadDisabledFromInfo": "True",
    "FFlagBatchAssetApi": "True",
    "FFlagBeamCrashFix2": "True",
    "FFlagBestProximatePartFix": "True",
    "FFlagBgUpdateRedirectsHttpErrBase64Body": "True",
    "FFlagBorderSizeRespectUIScale": "True",
    "FFlagCFrameFromMatrix": "True",
    "FFlagCLI18241": "True",
    "FFlagCLI18241A": "True",
    "FFlagCLI18241B": "True",
    "FFlagCLI19115": "False",
    "FFlagCLI21289": "True",
    "FFlagCSGv2BalanceExponents": "False",
    "FFlagCSGv2ControlSignificands": "False",
    "FFlagCSGv2EnableEmptyMeshError": "True",
    "FFlagCSGv2EnablePerPrimitiveBoxMaps": "True",
    "FFlagCSGv2FixOrientationWhenSeparatingNegates": "True",
    "FFlagCSGv2ForceEnabled": "True",
    "FFlagCSGv2InGameEnabled": "True",
    "FFlagCSGv2UnionOrientationFromFirstPart": "True",
    "FFlagCSGv2UnparentPartsBeforeModifyingCFrames": "True",
    "FFlagCSGv2UseImprovedSphereAndCylinder": "True",
    "FFlagCSGv2UseIterativeSimplification": "True",
    "FFlagCacheableContentProviderCleanup": "True",
    "FFlagCallPlaceLauncherFromMainThread2": "True",
    "FFlagChangeInfoInNetworkMenu": "True",
    "FFlagChatServiceAnalyticsOnFilterStringCalls": "False",
    "FFlagChatServiceInstallerExemptLocalizationFromAnalytics": "True",
    "FFlagCheckRequestingTeleportAtTeleportImplBeginning": "True",
    "FFlagClampCharacterScales": "True",
    "FFlagCleanupIsInStudio": "True",
    "FFlagClickDetectorCursorIconEnabled": "True",
    "FFlagClientFireEventPlaceLauncherFail3": "True",
    "FFlagConnectionScriptEnabled": "True",
    "FFlagConnectionScriptEnabled_PlaceFilter": "False;1608755154",
    "FFlagContentProviderTempDirWithPid2": "True",
    "FFlagCoreScriptTranslateGameText2": "True",
    "FFlagCoreScriptsUseLocalizationModule": "True",
    "FFlagCrashReporterNew": "False",
    "FFlagDataModelForwardForceLocaleIds": "True",
    "FFlagDatamodelServicesConnectionFix2": "True",
    "FFlagDebugCSGExportFailure": "False",
    "FFlagDebugClientNetworkPerPlaceMetrics": "False",
    "FFlagDebugClientNetworkPerPlaceMetrics_PlaceFilter": "True;1818;3498890;189707",
    "FFlagDebugGraphicsIntelCrash": "False",
    "FFlagDebugUseDefaultGlobalSettings": "True",
    "FFlagDelayPurchasePromptActivation": "True",
    "FFlagDeterministicJointSort": "True",
    "FFlagDevConsoleTabMetrics": "True",
    "FFlagDisablePlayerScriptWhenDisconnected": "True",
    "FFlagDonotAllowTeleportInRobloxStudio": "True",
    "FFlagDontTagsMeBro": "True",
    "FFlagEnableAEAndroidBackButton": "True",
    "FFlagEnableAndroidVsync": "True",
    "FFlagEnableAutomaticScalingEnabled": "True",
    "FFlagEnableAvatarEditoriOSTablet": "True",
    "FFlagEnableGetBoundingBox": "True",
    "FFlagEnableGuiLayerCollectorResetOnRespawn": "True",
    "FFlagEnableImageTilingInGUI": "True",
    "FFlagEnableLoadingHUDOniOSForGameShare": "True",
    "FFlagEnableLuaAppFormFactorAndPlatformV355": "True",
    "FFlagEnableLuaEventStreamRelease": "True",
    "FFlagEnableLuaGamesListSortsFix": "True",
    "FFlagEnableLuaSortTokensManualRefresh": "True",
    "FFlagEnableMouseUpEventFireForCurrentDragGuiObj": "True",
    "FFlagEnableNewChatApi": "True",
    "FFlagEnableNewDevConsole": "True",
    "FFlagEnableOnboardingMemoryAPI_PlaceFilter": "True;1817743405",
    "FFlagEnableReplaceBodyPartR15": "True",
    "FFlagEnableRobloxGuiEffect": "True",
    "FFlagEncodeIntShiftFix": "True",
    "FFlagExitProcessOnExit": "True",
    "FFlagExtendedHdrPrecision": "True",
    "FFlagFEForEveryone": "True",
    "FFlagFixBindActivateStackOrderCAS": "True",
    "FFlagFixCameraControlsWhileIdle": "False",
    "FFlagFixCameraControlsWhileIdle2": "True",
    "FFlagFixCollectionServiceCrash": "True",
    "FFlagFixCustomTeleScreen": "True",
    "FFlagFixFolderDescendantSelection": "True",
    "FFlagFixForcedRelayoutInTextLabel": "True",
    "FFlagFixG3DFpChecks": "True",
    "FFlagFixGamepadNavigationInVR": "True",
    "FFlagFixGuiStateTransitions7": "True",
    "FFlagFixHeadScales": "True",
    "FFlagFixIAdornableCollectorCrash3": "False",
    "FFlagFixIncorrectScrollingFrameBounds": "True",
    "FFlagFixInputCanSinkCAS": "True",
    "FFlagFixLineHandleAdornmentsNearPlane": "True",
    "FFlagFixLoadingScreenJankiness": "True",
    "FFlagFixOutOfBoundsMouseLocation": "True",
    "FFlagFixPlayerActionTypeOverride": "True",
    "FFlagFixPlayerlistFollowing": "True",
    "FFlagFixPluginDeactivation": "True",
    "FFlagFixPluginUnload": "False",
    "FFlagFixScalingValueRename": "True",
    "FFlagFixScalingValueRename_PlaceFilter": "False;370731277",
    "FFlagFixScalingValueReplication2": "True",
    "FFlagFixScalingValueReplication2_PlaceFilter": "True;2474528007;2477941234;2244319638",
    "FFlagFixScrollbarNotBeingDraggableWithUIPadding": "True",
    "FFlagFixScrollingFrameClipRect": "True",
    "FFlagFixSmallSurfaceGuiMouseInput": "True",
    "FFlagFixStaleBillboardGuiPosition2": "True",
    "FFlagFixTextureAtlasLineHeightOn4xDevices": "True",
    "FFlagFixUsersReducerDataLoss361": "True",
    "FFlagFixWindowsClientKeyboardLayoutHandling": "True",
    "FFlagFixWindowsRemoteCaptureHandling": "True",
    "FFlagFixXSwipe": "True",
    "FFlagForceSDLInitOnMainThread2": "False",
    "FFlagFreeCameraForAdmins": "True",
    "FFlagFreeCameraForDevelopers": "True",
    "FFlagFutureIsBrightPhase1_12": "True",
    "FFlagFutureIsBrightPhase1_13": "True",
    "FFlagFutureIsBrightPhase1_2": "True",
    "FFlagFutureIsBrightPhase1_2_PlaceFilter": "True;297878978;2514733396",
    "FFlagG3DRayCylinderintersectionTimeFix": "True",
    "FFlagGameExplorerCopyPath": "True",
    "FFlagGraphicsD3D11ConstantSizeClasses": "True",
    "FFlagGraphicsGL2DisableShadows": "False",
    "FFlagGraphicsGL3InstancingEnabled5": "True",
    "FFlagGraphicsGL3UseUBO3": "True",
    "FFlagGraphicsMetalPrivateMemory": "False",
    "FFlagGraphicsVulkanFixEmptyPasses2": "True",
    "FFlagGridMaterialFix": "True",
    "FFlagGuestFriendCheckFailImmediate": "True",
    "FFlagGuiRenderRemoveFix": "True",
    "FFlagHelpMenuShowPlaceVersion": "True",
    "FFlagHoverAndPressedTextureSwap": "True",
    "FFlagHttpClientDisconnectResultSignals": "True",
    "FFlagHttpClientRedirectCache": "True",
    "FFlagHttpHttpAsyncQueue2": "True",
    "FFlagHttpHttpAsyncQueueWeakFix": "True",
    "FFlagHttpParallelLimit": "True",
    "FFlagHttpQueueAsyncOnly": "True",
    "FFlagHttpReportCacheStatisticsNew": "True",
    "FFlagHttpReportStatisticsOnce": "True",
    "FFlagHttpSimpleGzip": "True",
    "FFlagHttpSkipQueueIfCached": "True",
    "FFlagHttpUrgentRequest": "True",
    "FFlagHttpUseContentCacheFlag3": "True",
    "FFlagHttpUseMinGzip": "False",
    "FFlagHttpUseMinPost": "True",
    "FFlagIWannaBeTheVeryBestThumbstick": "True",
    "FFlagIkDraggerCheckJointInKernel": "True",
    "FFlagInGameUIForceDefaultLocaleOnOSX": "True",
    "FFlagInGameUIForceDefaultLocaleOnWin10": "True",
    "FFlagInGameUIForceDefaultLocaleOnWin32": "True",
    "FFlagInfluxDbAndroidSeriously": "True",
    "FFlagInsertInstanceRecommendedList": "False",
    "FFlagInterpolationAwareTargetTime": "True",
    "FFlagJoinTimeCounters": "True",
    "FFlagJoinTime_AvatarFastClusterSignal": "True",
    "FFlagJoinTime_AvatarTextureCompositorSignal": "True",
    "FFlagJoinTime_HttpQueuePrio": "True",
    "FFlagJoinTime_LocalUserAnimationPriority": "True",
    "FFlagJoinTime_LocalUserClusterPriority": "True",
    "FFlagJoinTime_LocalUserMeshPriority": "True",
    "FFlagJoinTime_LocalUserTexturePriority": "True",
    "FFlagJoinTime_PassTexturePriority": "True",
    "FFlagKeyframeSequenceApplyZeroWeight": "True",
    "FFlagKeyframeSequenceEnableFrozen": "True",
    "FFlagKeyframeSequenceProviderIsStudioFix": "True",
    "FFlagLoadAvatarEditorTranslations": "True",
    "FFlagLoadTheLoadingScreenFaster": "False",
    "FFlagLoadTimesFromAppShellReporter": "True",
    "FFlagLoadingScreenUseLocalizationTable": "True",
    "FFlagLocalesInUserInfoOnAndroid": "True",
    "FFlagLocalesInUserInfoOniOS": "True",
    "FFlagLocalizationAppendFunctionsAlwaysAppend": "True",
    "FFlagLocalizationServiceIgnoreNonText": "True",
    "FFlagLocalizationServiceIgnoreNonText_PlaceFilter": "True;1117775855",
    "FFlagLocalizationServiceUseNewTextScraper": "True",
    "FFlagLocalizationServiceUseNewTextScraper_PlaceFilter": "True;1117775855",
    "FFlagLockAccessToDebuggerLuaStateMap": "True",
    "FFlagLogCorectTeleportFailureMessage2": "True",
    "FFlagLuaAppCancelSearchOnBackButtonPressed": "True",
    "FFlagLuaAppFriendshipCreatedSignalREnabledV355": "True",
    "FFlagLuaAppGamesPagePreloadingDisabled": "False",
    "FFlagLuaAppLegacyInputDisabledGlobally2": "True",
    "FFlagLuaAppSetNetworkErrorToasts": "True",
    "FFlagLuaAppSiteMessageBannerEnabled": "True",
    "FFlagLuaAppStoreStatusBarHeight": "True",
    "FFlagLuaAppUseImageSets": "True",
    "FFlagLuaAppUseRequestInternalWrapper3": "True",
    "FFlagLuaChatAssetCardsSelfTerminateConnection": "True",
    "FFlagLuaChatCheckIsChatEnabled": "True",
    "FFlagLuaChatCheckWasUsedRecentlyV361": "True",
    "FFlagLuaChatConsistentMarkAsRead": "True",
    "FFlagLuaChatFlexibleTitleWidth": "True",
    "FFlagLuaChatFriendIconRefactor": "True",
    "FFlagLuaChatIcebreaker": "True",
    "FFlagLuaChatInfiniteRelayoutRecursionFixV360": "True",
    "FFlagLuaChatInputBarRefactor": "True",
    "FFlagLuaChatLoadGameLinkCardInChatAnalytics": "True",
    "FFlagLuaChatNewPageSlidingTransition": "True",
    "FFlagLuaChatNotificationButtonEnabled": "True",
    "FFlagLuaChatPerformanceTracking": "True",
    "FFlagLuaChatPlayTogetherJoinGameInstance": "True",
    "FFlagLuaChatPlayTogetherUseRootPresence": "True",
    "FFlagLuaChatToSplitRbxConnectionsV362": "True",
    "FFlagLuaChatUseCppTextTruncation": "False",
    "FFlagLuaChatUseNewFriendsAndPresenceEndpointV356": "True",
    "FFlagLuaCorrectContextualMenuPosition": "True",
    "FFlagLuaDebuggerBreakOnError": "True",
    "FFlagLuaGameCarouselAddLoadingStates": "False",
    "FFlagLuaHomeAndGamesPageHandleFailedRequests": "True",
    "FFlagLuaHomeControlNativeBottomBar": "True",
    "FFlagLuaHomePageDataFetchRefactor": "True",
    "FFlagLuaHomeRemoveGameDataRefreshingForPeopleListContextualMenuV362": "True",
    "FFlagLuaInviteGameUsesInviteThunk": "True",
    "FFlagLuaMathLibUseNewRNG": "True",
    "FFlagLuaSearchPageHandlesFailedRequests2": "True",
    "FFlagLuaUseUtf8TextTruncation": "True",
    "FFlagLuaUseWebPageWrapperForGameDetails": "True",
    "FFlagMacClientUseCrashpadLibrary": "False",
    "FFlagMemoryFromAppShellReporterAndroid": "False",
    "FFlagMemoryFromAppShellReporterIOS": "True",
    "FFlagMeshWriteNullFix": "True",
    "FFlagMonitorBatteryLevel": "True",
    "FFlagMorphingHumanoidDescriptionSystemEngine": "True",
    "FFlagNavigationDebugDrawIterateSpiral": "True",
    "FFlagNavigationFixCheckOcclusionAsyncV2": "True",
    "FFlagNavigationFixConsecutiveJumps": "True",
    "FFlagNavigationFixMeshMerging": "True",
    "FFlagNavigationFixShutdown": "True",
    "FFlagNavigationPathBlockedEventEnabled2": "True",
    "FFlagNavigationVariableAgentSize2": "True",
    "FFlagNetworkDeserializePacketsInAJob": "True",
    "FFlagNewABTestingEndpoint": "True",
    "FFlagNewConstraintVisualsEnabled": "True",
    "FFlagNewDefaultScriptSource": "True",
    "FFlagNoFaceHeadMeshTag": "True",
    "FFlagNotificationScript2UseFormatByKey": "True",
    "FFlagOnDisconnectHttpNew": "True",
    "FFlagOnDisconnectHttpPrio": "True",
    "FFlagOnlySinkMouseMoveScrollIfCanScroll": "True",
    "FFlagOrientationConstraintPrimaryAxisOnlyFix": "True",
    "FFlagOutputWidgetFindEnabled": "False",
    "FFlagPGSAdaptiveCollisionMarginFixEnabled": "False",
    "FFlagPGSAlign2AxesInitBasis": "True",
    "FFlagPGSOrientationConstraintAngleComputationFix": "True",
    "FFlagPackagesEnabled": "True",
    "FFlagPassDataModelDPIScale": "True",
    "FFlagPassDataModelInitializationParams": "True",
    "FFlagPassDataModelInitializationParamsEvenMore": "True",
    "FFlagPassIsPublicChatOnFilterMessage": "True",
    "FFlagPhysicsAnalyzerAnalyticsEnabled": "True",
    "FFlagPhysicsAnalyzerUsed": "True",
    "FFlagPlaceLauncherConnectGameShutdownSignal": "True",
    "FFlagPlaceLauncherSetCurrentGameEntryOnceOnTeleport": "True",
    "FFlagPlayerAcceptPlayerScriptsStatus": "True",
    "FFlagPluginGuiGetRelativeMousePositionApi": "True",
    "FFlagPreRetinaCompositionEnabled": "True",
    "FFlagQuantumGui4": "True",
    "FFlagQuantumGui4_PlaceFilter": "False;1748877807;137877687;755776245;691884101;1447501408;406773301;258258996;651474220;936754492;1122507250;654732683",
    "FFlagQuantumGuiEnabledInGame4": "True",
    "FFlagQuantumGuiEnabledInGame4_PlaceFilter": "False;1748877807;137877687;755776245;691884101;1447501408;406773301;258258996;651474220;936754492;1122507250;654732683",
    "FFlagRCCSupportTeamTest": "True",
    "FFlagRakNetSupportIpV6": "True",
    "FFlagRandomType": "True",
    "FFlagRapidJson110_2": "False",
    "FFlagRccUseNewSharedDynamicFlagReloader": "True",
    "FFlagRecalculateAbsolutePlacementFix": "True",
    "FFlagRecordInGameDeaths": "False",
    "FFlagRemoveInputEventsMutex": "True",
    "FFlagRemoveKeyboardOnShutdownIOS": "True",
    "FFlagRemoveLoadingHUDOniOS": "True",
    "FFlagRenderFixEmojiPadding": "True",
    "FFlagRenderIC1BouncingEnabled": "True",
    "FFlagRenderIC2VoxelizerUpdatesEnabled": "True",
    "FFlagRenderInstancingDeferUpdates2": "True",
    "FFlagRenderInstancingEnabled8": "True",
    "FFlagRenderInstancingIC2Enabled2": "True",
    "FFlagRenderLightGridEfficientUploads": "True",
    "FFlagRenderLightGridFixAniso": "True",
    "FFlagRenderMinLightRadius": "True",
    "FFlagRenderNoLightInfluenceOnTop": "True",
    "FFlagRenderPartInstancingEnabled6": "True",
    "FFlagRenderRestrictHeads5": "True",
    "FFlagRenderUICmdBuffer2": "True",
    "FFlagRenderUICmdBuffer3": "True",
    "FFlagRenderVoxelUnderwaterFog": "True",
    "FFlagRenderingOnTopWithDepthEnabled": "True",
    "FFlagReportAbuseMenuDescriptionFix": "True",
    "FFlagReportAutoJointsModeJoinAll": "True",
    "FFlagReportInGameAssetSales": "True",
    "FFlagReportJoinAllCount": "True",
    "FFlagReportPrimitiveSortChangedCount": "False",
    "FFlagReportRuntimeJoinCount": "True",
    "FFlagReportTimestampToEventSystem": "True",
    "FFlagResetMouseDeltaFix": "True",
    "FFlagResetUserInput": "False",
    "FFlagRightClickContextIncludeUI": "True",
    "FFlagRoundInAdorn2": "True",
    "FFlagRoundInAdorn2_PlaceFilter": "True;966642236;1863446194;1381491115;2147711416;2099342453;801697386;2160953483;1907899252;2127688273;1915772117;1812510958;1621938214;282557436;2286024218;1921823969;1921830570;771903436;90007892;734564410;335047887;2197097402;2167204417;2143402865;2126748962;2379845779;2327413161;2350357280;2386982947;570460315",
    "FFlagRunningBaseClampAcceleration": "True",
    "FFlagRunningBaseUseNewAltitudePD": "True",
    "FFlagSIMDVoxelizerEnabled": "True",
    "FFlagScreenGuiOnTopOfCoreBlur": "True",
    "FFlagScrollToTopShortDistanceResponseFix": "True",
    "FFlagSendJoinTimesToDiag_PlaceFilter": "true;370731277",
    "FFlagServerStartMegaPhysicsJob": "True",
    "FFlagSessionReporterLock": "True",
    "FFlagSetMouseInputStateLater": "True",
    "FFlagSetPlaceIdInAdvance2": "False",
    "FFlagSettingsHubInviteReleaseStreamTimeAs10": "True",
    "FFlagSettingsHubInviteToGameDefaultThumbnailSize150x150": "True",
    "FFlagShadowBoxFix": "True",
    "FFlagShareGameToChatStatusAnalytics": "True",
    "FFlagShowPlaceholderTextWhileFocused3": "True",
    "FFlagSolverHotSwappingEnabled2": "True",
    "FFlagSpringConstraintInGameAdornFix": "True",
    "FFlagStatUtilsUseFormatByKey": "True",
    "FFlagStudioABTestFramework": "True",
    "FFlagStudioAddRemovePluginWindowRendering": "True",
    "FFlagStudioAnimationEditorIKMode": "True",
    "FFlagStudioAnimationEditorScaleKeys": "True",
    "FFlagStudioClearSelectionExitsAttachmentTool": "True",
    "FFlagStudioEnableWebKitPlugins": "True",
    "FFlagStudioNewLimit": "True",
    "FFlagStudioShowTutorialsByDefault": "True",
    "FFlagStudioTutorialSeeAll": "True",
    "FFlagStudioUseLuaGameSettingsDialog": "True",
    "FFlagTSMk2ThrottleStreamJob": "True",
    "FFlagTaskSchedulerSTDThreadwrapper": "True",
    "FFlagTextBoxOverrideManualFocusRelease": "False",
    "FFlagTextMeasureTemporaryPatch": "True",
    "FFlagTextScraperTypewriterEffectFix": "True",
    "FFlagTextScraperTypewriterEffectFix_PlaceFilter": "True;1117775855",
    "FFlagThwartPurchasePromptScams": "True",
    "FFlagThwartPurchasePromptScamsGamepad": "True",
    "FFlagTighterCylinderBoundingSpheres": "True",
    "FFlagTrackCurlTimeProfile": "True",
    "FFlagUIShiftScrollHorizontal2": "True",
    "FFlagUSC180727A": "True",
    "FFlagUSC180727C": "True",
    "FFlagUSC180727D": "True",
    "FFlagUnlockMouseIfKicked": "True",
    "FFlagUnlockedTopbarTransparency": "True",
    "FFlagUrlSupportNewGamesAPI": "True",
    "FFlagUseActivatedForMouseButton1Click": "True",
    "FFlagUseAdvancedCharacterScales3": "True",
    "FFlagUseAvatarAPIAvatarFetchV2": "True",
    "FFlagUseLDLPGSSolver4": "True",
    "FFlagUseLDLPGSSolver4_PlaceFilter": "False;1636712",
    "FFlagUseLargerFontAtlasOn3xDevices": "False",
    "FFlagUseLuaGamesPageOniPad": "True",
    "FFlagUseLuaGamesPageOniPhone": "True",
    "FFlagUseLuaHomePageOniPad": "True",
    "FFlagUseLuaHomePageOniPhone": "True",
    "FFlagUseMatrix3ForInertiaTensor2": "True",
    "FFlagUseNewStructurePlayerScripts": "True",
    "FFlagUseNewStructurePlayerScripts_PlaceFilter": "False;447452406;1345139196;1599679393;1417427737;2204210120",
    "FFlagUseOptimizedGetPartsObscuringTarget": "True",
    "FFlagUseSafeZoneOffsets": "True",
    "FFlagUseUnorderedMapForSelectionConnections": "True",
    "FFlagUserAllCamerasInLua": "True",
    "FFlagUserAnimationSpeedDampening": "True",
    "FFlagUserBetterInertialScrolling": "False",
    "FFlagUserEnableDynamicThumbstickIntro_PlaceFilter": "True;1817743405",
    "FFlagUserFixChatMessageLogPerformance": "False",
    "FFlagUserHttpAPIVisible": "True",
    "FFlagUserInGameChatUseNewFilterAPIV2": "True",
    "FFlagUserInputServicePipelineMacClient": "True",
    "FFlagUserInputServicePipelineStudio": "True",
    "FFlagUserInputServicePipelineWindowsClient": "True",
    "FFlagUserIsNowADynamicThumbstick": "True",
    "FFlagUserJumpButtonPositionChange": "True",
    "FFlagUserNavigationClickToMoveUsePathBlocked": "True",
    "FFlagUserNavigationFixClickToMoveInterruption": "True",
    "FFlagUserNavigationFixClickToMoveJump": "True",
    "FFlagUserNewCameraRaycastingAPIsEnabled": "True",
    "FFlagUserNewPoppercam": "False",
    "FFlagUserNewPoppercam_PlaceFilter": "False;855499080;606849621;537413528;402122991",
    "FFlagUserNoCameraClickToMove": "True",
    "FFlagUserNoUpdateOnLoop": "True",
    "FFlagUserRbxUtilityCreateSetParentLast": "True",
    "FFlagUserShouldClipInGameChat": "True",
    "FFlagUserToolR15Fix": "True",
    "FFlagUserUseCachedFriendChecksForChat": "False",
    "FFlagUserUseNewControlScript": "True",
    "FFlagVideoDocumentationPluginEnabled": "True",
    "FFlagWeldConstraintAdornHighlightConnectedParts": "True",
    "FFlagWeldConstraintAdornImprovements": "True",
    "FFlagWindowsClientAllowUnregisteredFlags": "True",
    "FFlagWindowsClientGetLocaleIdsFromCommandLine": "True",
    "FIntAntiSpamSpamLimit": "1000",
    "FIntAppShellFPSReportPeriod": "120",
    "FIntAppShellMemoryReportPeriodicity": "120",
    "FIntCameraFarZPlane": "100000",
    "FIntCameraMaxZoomDistance": "400",
    "FIntGamePerfMonitorPercentage": "10",
    "FIntGraphicsVulkanMinAndroidVersion": "24",
    "FIntJointTime_TextureCooldown": "0",
    "FIntLocalizationAnalyticsSamplesPerMillion": "50000",
    "FIntMaxCameraMaxZoomDistance": "100000",
    "FIntNewDevConsoleMaxHttpCount": "300",
    "FIntNewDevConsoleMaxLogCount": "500",
    "FIntNumSmoothingPasses": "3",
    "FIntPGSAngularDampingPermilPersecond": "950",
    "FIntPGSPStageStiffnessWorseFitnessThreshold": "2",
    "FIntPGSVStageStiffnessAggressiveValue": "99995",
    "FIntPGSVStageStiffnessConservativeValue": "99000",
    "FIntPGSVStageStiffnessWorseFitnessThreshold": "2",
    "FIntPartMinSizeMul1000": "50",
    "FIntPercentReportingByCountryCode": "100",
    "FIntPercentReportingGamesListRTT": "5",
    "FIntPercentReportingGamesSortsRTT": "50",
    "FIntPercentReportingNetworkProfileAfterStartup": "20",
    "FIntRegLambda": "1400",
    "FIntSendScreenOrientationToEventIngestHundredthsPercentage": "100",
    "FIntStartupInfluxHundredthsPercentage": "100",
    "FIntStudioInsertDeletionCheckTimeMS": "30000",
    "FIntTeleportMethodAnalyticsHundredthPct": "100",
    "FIntValidateLauncherPercent": "100",
    "FIntWeldConstraintAdornSize": "10",
    "FIntZoomOutDistance": "500",
    "FLogBrowserActivity": "3",
    "FLogCloseDataModel": "3",
    "FLogDXVideoMemory": "4",
    "FLogFullRenderObjects": "0",
    "FLogGraphics": "6",
    "FLogHangDetection": "3",
    "FLogLuaBridge": "2",
    "FLogNetwork": "7",
    "FLogNetworkItemQueueDtor": "1",
    "FLogPlayerShutdownLuaTimeoutSeconds": "1",
    "FLogVR": "6",
    "FStringABTestNameIPhoneLuaGameAndHome": "iPhone.AllUsers.WebToLuaTransitionGameAndHome2",
    "FStringGraphicsVulkanBlacklist": "SM-T713;XT1650;ZT500KL",
    "FStringSettingsHubInviteToGameThumbnailSize": "Size150x150",
    "FStringStudioTutorialsTOCUrl": "http://web.archive.org/web/20190107002714/http://wiki.roblox.com/index.php?title=Studio_Tutorials_Landing&studiomode=true",
    "FStringStudioTutorialsUrl": "http://web.archive.org/web/20190107002714/http://wiki.roblox.com/index.php?title=Studio_Tutorials_Test&studiomode=true",
    "GoogleAnalyticsLoadStudio": "1",
    "PublishedProjectsPageHeight": "535",
    "PublishedProjectsPageUrl": "/ide/publish",
    "PublishedProjectsPageWidth": "950",
    "SFFlagFixBallRaycasts": "True",
    "SFFlagFixHats": "True",
    "SFFlagFixRaysInWedges": "True",
    "SFFlagReplicateInterpolateRelativeHumanoidPlatformsMotion": "True",
    "SFFlagReplicateInterpolateRelativeHumanoidPlatformsMotion_PlaceFilter": "True;1743435700;860752518;463915360;1863446194;1512094341;163865146;1213026131;1218315440;504457989;2219724314;1535168527;2104018654;918416946;70098735;1079180573;2245202927;570766117;2256357622;1661410839;84402258;1921823969;1921830570;1447501408;1817743405;878230612;156220906;606849621",
    "SFFlagUseNativePathWaypoint": "True",
    "StartPageUrl": "/ide/welcome",
    "VideoPreRollWaitTimeSeconds": "45",
    "FFlagStudioAnimationEditorUseNewThemeAPIV2": "True",
    "DFFlagScrollWhenInsideFocusedTextBox": "True",
    "DFFlagTextBoxesNeverSinkMouseEvents": "True",
    "FFlagRenderStreamerUpload": "False",
    "FFlagGraphicsVulkanKeepCommandBuffers": "True",
    "FFlagResetUserInput2": "True",
    "FIntGraphicsVulkanMinAndroidVersionNewPacks": "25",
    "FFlagGraphicsVulkanUseNewPacks5": "True",
    "FIntGraphicsVulkanMinAndroidVersionPVR": "28",
    "DFFlagDebugEnableRemoteProfiling": "False",
    "FFlagDataModelSetUniverseIdYieldFunction": "True",
    "DFIntLightingTechnologyInfluxHundredthsPercentage": "10",
    "DFFlagFixForPhoenix": "False",
    "FFlagHttpServiceWorldsMostOverkillFlagForMovingCodeFourLines": "True",
    "SFFlagEnableRootPriority": "True",
    "SFFlagPartMasslessEnabled": "True",
    "FFlagFlyweightServiceDataRecievedCallbackCrashFixEnabled": "True",
    "FFlagApsDebugClient2": "True",
    "SFFlagKeepRedundantWeldsExplicit": "True",
    "FFlagStudioFixPackageLinkManagementCastingError": "True",
    "FFlagUserNewPoppercam3": "True",
    "DFFlagStudioFixPublishedUnionsInUndoRedoStack": "True",
    "FFlagLuaChatSharedGamesListCrashFix": "True",
    "FFlagLuaChatSharedGameItemRefactorV365": "True",
    "FFlagLuaHomePageShowAddFriendsButtonV361": "True",
    "FFlagUSC24644": "True",
    "FFlagStudioReplaceEnableDisableTeamCreateEndpoints": "True",
    "DFFlagReportStreamingEnabledToInflux": "True",
    "FFlagLuaChatScreenManagerAlwaysUpdatesWithDefaultsV365": "False",
    "DFFlagCSGMeshLevelOfDetail_Fix2": "True",
    "DFIntCSGLevelOfDetailSwitchingDistanceL12": "500",
    "DFFlagGetBundleDetailsAPI": "True",
    "DFFlagUseNewReplaceHttpWithHttpsFunction": "True",
    "DFFlagCLI120342p5": "True",
    "FFlagUserNewPoppercam3_PlaceFilter": "False;1997193809;734159876",
    "DFFlagLuaInstanceBridgeLabelLiteral": "True",
    "FFlagRenderVoxelWaterFix2": "True",
    "DFFlagAllowPackageLinkAncestoryClone": "True",
    "FFlagLinearFX2": "True",
    "FIntHttpCurlMaxCachedHandlesPerHost": "8",
    "DFFlagHttpSocialServiceType": "True",
    "FFlagFixVersionContainer": "True",
    "DFFlagReportPhysicsStatsToHUD": "True",
    "FFlagShowGothamFonts": "True",
    "DFFlagCSGMeshLevelOfDetailV2_PlaceFilter": "True;2434889832;2568147212",
    "DFIntCSGLevelOfDetailSwitchingDistance_PlaceFilter": "250;2434889832;2568147212",
    "DFIntCSGLevelOfDetailSwitchingDistanceL12_PlaceFilter": "500;2434889832;2568147212",
    "FFlagServerGeneratesPlayer5": "False",
    "FFlagUseNewGameCardDesign": "True",
    "FFlagDeferTerrainUpdate2": "False",
    "DFFlagVerifyWorldInTryFloor": "True",
    "FFlagResetTabBarVisibilityOnAppShellRestart": "True",
    "DFFlagTerrainWeldToolValidCFrames": "True",
    "DFFlagDeferTerrainUpdate2": "True",
    "DFFlagTextScraperUseUpdatedHttpApi": "True",
    "DFIntLocalizationServiceContentLoadErrorHundredthsPercentage": "1000",
    "DFFlagAvatarLoadingBetterRandomReporting": "True",
    "FFlagRapidJson110_BgUpdater": "True",
    "FFlagRenderEmitterRecomputeOnChange": "False",
    "FFlagFixTextureCompositorFramebufferManagement": "False",
    "FFlagFixTextureCubeFramebuffers": "True",
    "DFFlagCSGMeshLevelOfDetailV2": "True",
    "SFFlagFixDictionaryScopePlatformsReplication": "True",
    "FFlagFixUserCarouselWindowing": "True",
    "FFlagUserNewDefaultCameraAngle": "True",
    "FFlagCorescriptLocalizationExpertIcon": "False",
    "FFlagCoreScriptBetterACMFriendStatusChecks": "True",
    "FFlagCoreScriptFixPlayerDropdownUnfriend": "True",
    "DFFlagDebugEnableRemoteProfiling2": "True",
    "DFFlagTrackSlowDns": "True",
    "FFlagTestForBadNormal": "True",
    "FFlagRenderCacheUICmdBuffers": "True",
    "DFFlagRemoveNetworkOwnershipFromFilter": "True",
    "DFFlagScriptContextTraceLocalTime": "True",
    "DFFlagShowGravityStat": "True",
    "DFFlagContactManifoldCountReportingEnabled": "True",
    "FFlagLDLSolverFixOutOfMemoryCrashes": "True",
    "FFlagRapidJson110_Reader": "True",
    "FFlagCheckGameValidityInDoTeleport": "True",
    "DFFlagEnableRemoteProfilingForDevConsole": "True",
    "FFlagRapidJson110_Writer": "True",
    "DFIntCSGv2LodsToGenerate": "3",
    "FFlagForceSDLInitOnMainThread3": "True",
    "FFlagForceSetSizeOfErrorPrompt": "True",
    "FFlagForceMouseInputWhenPromptPopUp": "False",
    "FFlagLazyCreateErrorPrompt": "True",
    "FFlagDevConsoleOnTopOfCoreBlur": "True",
    "DFFlagGetTranslatorForPlayerAsyncEnabled": "True",
    "FFlagLuaAppRouterControlsTabBarVisibility": "True",
    "DFFlagSupportYouTubeInAppDataModelIfRbxCdnAllowed": "True",
    "FFlagLuaAppShimmerAnimationRedesign": "True",
    "FFlagLuaAppToastRedesign": "True",
    "FFlagLuaAppExtendOverlayToFullScreen": "True",
    "FFlagLuaAppExtendOverlayToFullScreen2": "True",
    "FFlagLuaGameDetailsPolishV366": "True",
    "FFlagLuaGameDetailsFixMoreMenuCrash": "True",
    "FFlagReimplementUIScaleDirectParentBehavior": "True",
    "FFlagLuaAppFixDropdownLabelOverflow": "True",
    "DFFlagPhysicsSkipNonRealTimeHumanoidForceCalc2": "True",
    "FFlagQuantumGuiClipScreenGuiToViewport2": "False",
    "FFlagFixUIScaleClipRectCalculation": "True",
    "FFlagFixForLuaSubpageNavigationOnForeground": "False",
    "FIntMaxLevelForAnchored": "3",
    "FStringABTestNameIPhoneLuaGameDetails": "iPhone.AllUsers.LuaGameDetails2",
    "FFlagDontLoadCoreScriptsFromRenderScheduler2": "False",
    "FFlagFixLoadTimeReporting": "True",
    "FFlagReportToDiagByCountryCodeUsesRequestType": "True",
    "FFlagDontUseSystemRand": "True",
    "FFlagUserJSONConvertInfAndNanToNull": "True",
    "FIntLuaHomePageShowFriendAvatarFace150By150V366": "75",
}


CERT = """-----BEGIN CERTIFICATE-----
MIIRkDCCEHigAwIBAgIUURBd1fx4MvdFFvv4re9FfJ4ZffswDQYJKoZIhvcNAQEL
BQAwfjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5ZMREwDwYDVQQHDAhOZXcgWW9y
azEbMBkGA1UECgwSUm9ibG94IENvcnBvcmF0aW9uMRIwEAYDVQQDDAlsb2NhbGhv
c3QxHjAcBgkqhkiG9w0BCQEWD3Rlc3RAUm9ibG94LmNvbTAeFw0yMzAzMjEwMzQ1
MjRaFw0zMzAzMTgwMzQ1MjRaMH4xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJOWTER
MA8GA1UEBwwITmV3IFlvcmsxGzAZBgNVBAoMElJvYmxveCBDb3Jwb3JhdGlvbjES
MBAGA1UEAwwJbG9jYWxob3N0MR4wHAYJKoZIhvcNAQkBFg90ZXN0QFJvYmxveC5j
b20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDU/FiWdpCOOtCIjcUr
PwzXjIDayYGAIRimRytYR9RxnMuH6UL5K87PlAFH56WQXUdKnD1Q4CRQ8tcKoX1t
KTf5OnMFRtr9bDiVxTVrcXPvoNNINT38390ElquCPp+7l/Ha2uhSMP5bTfppj4Ab
MUV0+nIXG2UPQQ0glRWas0ChqJDSETAeEGAZVkCAbhTsDI+YLIATfB8Ocl42QZxY
ndk0vMbR1ist9Ad3Q53i6i2hmbrmyGlet18K15+GdwcGRD4qBnfOjBdSblyD/h6F
VVPkkFY4h6hcCCvf4sUBqn0WB0xvr2z5id6y0IeGp2+vxS+4X36rCxKfloLB6Uth
YfP1AgMBAAGjgg4EMIIOADAdBgNVHQ4EFgQUUkegzKAK9OwkLcIqSCW7gGdIK1Yw
gacGA1UdIwSBnzCBnKGBg6SBgDB+MQswCQYDVQQGEwJVUzELMAkGA1UECAwCTlkx
ETAPBgNVBAcMCE5ldyBZb3JrMRswGQYDVQQKDBJSb2Jsb3ggQ29ycG9yYXRpb24x
EjAQBgNVBAMMCWxvY2FsaG9zdDEeMBwGCSqGSIb3DQEJARYPdGVzdEBSb2Jsb3gu
Y29tghRREF3V/Hgy90UW+/it70V8nhl9+zAJBgNVHRMEAjAAMAsGA1UdDwQEAwIF
oDCCDO0GA1UdEQSCDOQwggzgghVyb2Jsb3gucm9ibG94bGFicy5jb22CGXd3dy5y
b2Jsb3gucm9ibG94bGFicy5jb22CLnZlcnNpb25jb21wYXRpYmlsaXR5LmFwaS5y
b2Jsb3gucm9ibG94bGFicy5jb22CMCoudmVyc2lvbmNvbXBhdGliaWxpdHkuYXBp
LnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIpZ2FtZXBlcnNpc3RlbmNlLmFwaS5yb2Js
b3gucm9ibG94bGFicy5jb22CH3VzZXJzLmFwaS5yb2Jsb3gucm9ibG94bGFicy5j
b22CGyouYXBpLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIqKi5jbGllbnRzZXR0aW5n
cy5hcGkucm9ibG94LnJvYmxveGxhYnMuY29tgiQqLnN0dWRpby1lY3N2Mi5yb2Js
b3gucm9ibG94bGFicy5jb22CGiphcGkucm9ibG94LnJvYmxveGxhYnMuY29tghoq
d2ViLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIdKnN0YXRpYy5yb2Jsb3gucm9ibG94
bGFicy5jb22CGSpqcy5yb2Jsb3gucm9ibG94bGFicy5jb22CGipjc3Mucm9ibG94
LnJvYmxveGxhYnMuY29tgh0qaW1hZ2VzLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIc
KnNldHVwLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIsKmVwaGVtZXJhbGNvdW50ZXJz
LmFwaS5yb2Jsb3gucm9ibG94bGFicy5jb22CGSp0aS5yb2Jsb3gucm9ibG94bGFi
cy5jb22CHiplY3MuYXBpLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIgKmFzc2V0Z2Ft
ZS5yb2Jsb3gucm9ibG94bGFicy5jb22CHCplY3N2Mi5yb2Jsb3gucm9ibG94bGFi
cy5jb22CJipnYW1lcGVyc2lzdGVuY2Uucm9ibG94LnJvYmxveGxhYnMuY29tgiYq
bWFya2V0cGxhY2UuYXBpLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIeKm1ldHJpY3Mu
cm9ibG94LnJvYmxveGxhYnMuY29tghsqYXV0aC5yb2Jsb3gucm9ibG94bGFicy5j
b22CGyphcGlzLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYITKmFwaXMuc2ltdWxwb25n
LmNvbYIdKmxvY2FsZS5yb2Jsb3gucm9ibG94bGFicy5jb22CICphYnRlc3Rpbmcu
cm9ibG94LnJvYmxveGxhYnMuY29tghwqdXNlcnMucm9ibG94LnJvYmxveGxhYnMu
Y29tgioqdHdvc3RlcHZlcmlmaWNhdGlvbi5yb2Jsb3gucm9ibG94bGFicy5jb22C
EipsbXMuc2ltdWxwb25nLmNvbYIbKmNoYXQucm9ibG94LnJvYmxveGxhYnMuY29t
gh8qY29udGFjdHMucm9ibG94LnJvYmxveGxhYnMuY29tgiQqbm90aWZpY2F0aW9u
cy5yb2Jsb3gucm9ibG94bGFicy5jb22CJiphY2NvdW50c2V0dGluZ3Mucm9ibG94
LnJvYmxveGxhYnMuY29tghoqYWRzLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIdKnRy
YWRlcy5yb2Jsb3gucm9ibG94bGFicy5jb22CHipmcmllbmRzLnJvYmxveC5yb2Js
b3hsYWJzLmNvbYImKnByaXZhdGVtZXNzYWdlcy5yb2Jsb3gucm9ibG94bGFicy5j
b22CHiplY29ub215LnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIcKmdhbWVzLnJvYmxv
eC5yb2Jsb3hsYWJzLmNvbYIfKnJlYWx0aW1lLnJvYmxveC5yb2Jsb3hsYWJzLmNv
bYIhKnRodW1ibmFpbHMucm9ibG94LnJvYmxveGxhYnMuY29tgh8qcHJlc2VuY2Uu
cm9ibG94LnJvYmxveGxhYnMuY29tgh0qZ3JvdXBzLnJvYmxveC5yb2Jsb3hsYWJz
LmNvbYIpKmFjY291bnRpbmZvcm1hdGlvbi5yb2Jsb3gucm9ibG94bGFicy5jb22C
HSpiYWRnZXMucm9ibG94LnJvYmxveGxhYnMuY29tgh8qZGV2Zm9ydW0ucm9ibG94
LnJvYmxveGxhYnMuY29tgiYqcHJlbWl1bWZlYXR1cmVzLnJvYmxveC5yb2Jsb3hs
YWJzLmNvbYIlKmNsaWVudHNldHRpbmdzLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIo
KmNsaWVudHNldHRpbmdzY2RuLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIoKmNsaWVu
dC10ZWxlbWVudHJ5LnJvYmxveC5yb2Jsb3hsYWJzLmNvbYImKmFkY29uZmlndXJh
dGlvbi5yb2Jsb3gucm9ibG94bGFicy5jb22CJCphc3NldGRlbGl2ZXJ5LnJvYmxv
eC5yb2Jsb3hsYWJzLmNvbYIdKmF2YXRhci5yb2Jsb3gucm9ibG94bGFicy5jb22C
HipiaWxsaW5nLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIeKmNhdGFsb2cucm9ibG94
LnJvYmxveGxhYnMuY29tgiMqY2RucHJvdmlkZXJzLnJvYmxveC5yb2Jsb3hsYWJz
LmNvbYIlKmNoYXRtb2RlcmF0aW9uLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIjKmNv
bnRlbnRzdG9yZS5yb2Jsb3gucm9ibG94bGFicy5jb22CHipkZXZlbG9wLnJvYmxv
eC5yb2Jsb3hsYWJzLmNvbYIiKmRpc2N1c3Npb25zLnJvYmxveC5yb2Jsb3hsYWJz
LmNvbYIqKmVjb25vbXljcmVhdG9yc3RhdHMucm9ibG94LnJvYmxveGxhYnMuY29t
gigqZW5nYWdlbWVudHBheW91dHMucm9ibG94LnJvYmxveGxhYnMuY29tgiEqZm9s
bG93aW5ncy5yb2Jsb3gucm9ibG94bGFicy5jb22CLypnYW1laW50ZXJuYXRpb25h
bGl6YXRpb24ucm9ibG94LnJvYmxveGxhYnMuY29tgh8qZ2FtZWpvaW4ucm9ibG94
LnJvYmxveGxhYnMuY29tgicqZ3JvdXBzbW9kZXJhdGlvbi5yb2Jsb3gucm9ibG94
bGFicy5jb22CICppbnZlbnRvcnkucm9ibG94LnJvYmxveGxhYnMuY29tgigqaXRl
bWNvbmZpZ3VyYXRpb24ucm9ibG94LnJvYmxveGxhYnMuY29tgikqbG9jYWxpemF0
aW9udGFibGVzLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIdKnBvaW50cy5yb2Jsb3gu
cm9ibG94bGFicy5jb22CHipwdWJsaXNoLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIi
KnB1bmlzaG1lbnRzLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIcKnNoYXJlLnJvYmxv
eC5yb2Jsb3hsYWJzLmNvbYIhKnRleHRmaWx0ZXIucm9ibG94LnJvYmxveGxhYnMu
Y29tgh0qdGhlbWVzLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIoKnRodW1ibmFpbHNy
ZXNpemVyLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYInKnRyYW5zbGF0aW9ucm9sZXMu
cm9ibG94LnJvYmxveGxhYnMuY29tgiMqdHJhbnNsYXRpb25zLnJvYmxveC5yb2Js
b3hsYWJzLmNvbYIlKnVzZXJtb2RlcmF0aW9uLnJvYmxveC5yb2Jsb3hsYWJzLmNv
bYIUKnZvaWNlLnNpbXVscG9uZy5jb22CICpmaWxlcy5hcGkucm9ibG94LnJvYmxv
eGxhYnMuY29tghQqcmNpdHkuc2ltdWxwb25nLmNvbYIkKmFidGVzdGluZy5hcGku
cm9ibG94LnJvYmxveGxhYnMuY29tghwqYnJvb20ucm9ibG94LnJvYmxveGxhYnMu
Y29tghQqYnJvb20uc2ltdWxwb25nLmNvbYIfKmNvbS1hcGlzLnJvYmxveC5yb2Js
b3hsYWJzLmNvbYIhKnBvaW50cy5hcGkucm9ibG94LnJvYmxveGxhYnMuY29tgiAq
dXNlcnMuYXBpLnJvYmxveC5yb2Jsb3hsYWJzLmNvbYIbKmRhdGEucm9ibG94LnJv
YmxveGxhYnMuY29tghwqc3dlZXAucm9ibG94LnJvYmxveGxhYnMuY29tghQqc3dl
ZXAuc2ltdWxwb25nLmNvbYIqKmdhbWVwZXJzaXN0ZW5jZS5hcGkucm9ibG94LnJv
YmxveGxhYnMuY29tghMqd3d3LnJvYmxveGxhYnMuY29tgg8qcm9ibG94bGFicy5j
b20wLAYJYIZIAYb4QgENBB8WHU9wZW5TU0wgR2VuZXJhdGVkIENlcnRpZmljYXRl
MA0GCSqGSIb3DQEBCwUAA4IBAQAmzUE98/MpTaUis9UaUYrmrEybnYuYl1cUlD5I
3a0BXIQeNhHqy+8JU6GA+o5CjAqR5syHa3Z0E2wZK89hDKgB5mwjhzWVmXAgDObX
KOCIL1LMaPnVM5ioY8Gyxpvk/Uwi2NZxcuB8aFgV3jYZ9xC1GmHZr2dMsn5DlsAV
pPF/TNTLTCnyBs7BArtVvRprPvMcdywgWPHA+Y/dkvvRuXieOuS+Y9wI+W90GpzC
xU52Qnxg2CDHw3FmcPqSRYz4+X1b5jKMh5dGz7cyD2xqouAjLAqXem+lii07RD0Z
uPzBoHNFFI+96JBfeOq3XlAk12EAzKqZO+FP4bd5iJtf2EmW
-----END CERTIFICATE-----"""

ALLOWED_MD5_HASHES = {
    "data": [
        "696224eb7537fbd4f684d05b30e7577b",
        "852c653bf5524615b0c16d08c7888489",
        "4f2255d00b498e8728394d44033375f1",
        "3228e65cf0a1a5efb11c1f50bc7e0e72",
        "2e3625c467dce071ef0366eb01f360b2",
        "d32f2f383eb067dbf4cef929e3720d22",
        "4f2255d00b498e8728394d44033375f1",
        "c51ce865a76f65834e0f9ed837ed1014",
        "f82d895f557e45d8ca779bd02729e8e5",
        "57b38d86235db049d8fbea3ac9ad0368",
        "a228078a3575428fb9bec8b158a563ca",
        "382edacdb1ea130cae005cda632490ca",
        "21560a2399a218dcfe56c7603bd37e20",
        "b41a1f6db3d35705d76ffad110add0b6",
        "7ffd87ec48186fd302d70762958792b6",
        "34394c67cf26408c24c4c68e447b465e",
        "da6e066c4db1df5561eb5a5eee06615a",
        "0395956deb4a80d4532e5cd8e24640e0",
        "cddb32998e61bb8a88d71b235bceb546",
        "034dad52f899219be7f974184908e7bb",
        "ba2258bbb24cd7ac772f8bc4bcc0c347",
        "12c35dfa6e96cf0cdbe45d2632806f54",
        "f1a5abf74dfc2c882ab95ca7c7d89129",
        "25cb4fa68e2b70a484a6cb7255a4a9d3",
        "08832dcb9f771b3436021de228017148",
        "641c9bee9332eea0bd91aae83ad206c9",
        "adc4983c75ab1b5b990f3bd30bf03949",
        "33fbddac973e93485c7e7d884d271724",
        "972dd1995553445d3bd9c7e4b8e08b26",
        "bff0c728dd9eb6224311be4628474791",
        "0904ee91b51adb48ae6d066606b469c2",
        "20a13e1db27108fb7fd1375366f1c0b5",
        "471c84516a9eead73c13d5369dc3fa51",
        "3231d09a8c3525a75e999789aa7d9df4",
    ]
}

JOIN_GAME_PRIVATE_KEY = b"MIICWwIBAAKBgQCtSajyR3WBwFEEdjvwGaWQ7yJ7DJF5kKe8A3RkHyeVOsHxJBiP1e6gjzQaLH0idxR4kuX2/ICrPSLymWmHA2hcGKtnrRxP1XAyBoDq4tyLCM4nuXMw3Z3XQm6+KxOkYnJI91fdWEbK3lz4B7X8V/OBALBqolp/q61wGHFULSLZ1QIDAQABAoGAbM+UBo5YeuEH/oU/ncR88kU2oY2Cy5LJwIVq0HO/pzT+Ey1XPvpWnPtO/CBzcvDTKeMUA8MKCHybNTqfyOea3zEEjqhRRKmKeUQ7RZjkJc4t/hOPrH5xSuUKSsycJBhgX2tUXS3lINcjdZTOFL7PRuiZdr5jUW3hQ5nPerDgkQECQQDYK1vf9a1n8Kh+D/ijv+Ms+BDbP1IjrviUqz3AfBdx5rkSMo78E6bFGeSDjX3LtDunDwrgGmzi/r2sDSkYnQpvAkEAzTeWeIxG46ZWevnX2CI82IcuvxAJow3dvlp+rm49YmI1DD0kJNhGXIUWWe7nkzCBHudAKGiVqbX0JWefuyvR+wJAeYs/mFh5zNR62I7AXcn5wQIl8DDVTW0HJgh2qzDauddhvgKhdMjT30UkwHchARVw6QjDM6iICsXy/bdUoRtDjwJAaYgagydwFQWnF1qAGw+QRrFN4sc2jXlF/OvAlabvPjbOnNqcSa5GkLGICvuGbvTUkbXOEnml7T46rTmatMAWHQJAd794C15/83bvOHE/TxD1Z/dXV9j5HGD8kHxtXivgV+mdM0r5KvTgiQnxnakg7NlXw7YgGI1btGffkWhYuEtQUw=="

HTTPD_SHOW_LOGS = True
