name: Build

on:
  push:
    branches:
      - main
    paths:
      - "Source/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: RFD-gnu-linux
            asset_name: RFD-gnu-linux
            sep: ':'
          - os: windows-latest
            artifact_name: RFD-windows
            asset_name: RFD-windows.exe
            sep: ';'
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        working-directory: Source
        run: |
          pip install pyinstaller==6.20.0
          pip install pillow==12.3.0
          pip install requests
          pip install -r requirements.txt

      - name: Build PyInstaller
        working-directory: Source
        run: pyinstaller RFD.spec

      - name: Rename Executable
        working-directory: Source
        shell: bash
        run: mv Source/dist/* dist/${{ matrix.asset_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.asset_name }}
          if-no-files-found: error
