name: Build

on:
  push:
    branches:
      - main
    paths:
      - "Source/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: RFD-linux
            asset_name: RFD-linux
            sep: ":"
          - os: windows-latest
            artifact_name: RFD-windows
            asset_name: RFD-windows.exe
            sep: ";"
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: venv setup
        uses: srvanderplas/action-setup-venv@v1.1.5

      - name: Create Virtual environment
        run: |
          rfd_venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m venv rfd_venv
          rfd_venv/Scripts/pip install pyinstaller requests
          rfd_venv/Scripts/pip install -r Source/requirements.txt
          rfd_venv/Scripts/pip install -r Source/requirements.dev.txt

      - name: Build PyInstaller
        shell: bash
        run: |
          rfd_venv/Scripts/pyinstaller \
            --name "RFD" \
            --onefile "$GITHUB_WORKSPACE/Source/_main.py" \
            --paths "$GITHUB_WORKSPACE/Source/" \
            --paths "$GITHUB_WORKSPACE/lib/*/site-packages" \
            --workpath "$GITHUB_WORKSPACE/PyInstallerWork" \
            --distpath "$GITHUB_WORKSPACE/dist" \
            --specpath "$GITHUB_WORKSPACE/PyInstallerWork/Spec" \
            ${{ hashFiles('Source/Icon.ico') != '' && format('--icon "{0}/Source/Icon.ico"', github.workspace) || '' }} \
            --add-data "$GITHUB_WORKSPACE/Source/*${{ matrix.sep }}Source" \
            --hidden-import requests \
            --hidden-import dracopy

      - name: Rename Executable
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-22.04" ]; then
            mv dist/RFD dist/${{ matrix.asset_name }}
            chmod +x dist/${{ matrix.asset_name }}
          else
            mv dist/RFD.exe dist/${{ matrix.asset_name }}
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.asset_name }}
          if-no-files-found: error
